void *createHead(void);
void *createNode(void);
void push(void *head, void *newNode);
void clearList(void *head);
void removeNode(void *head, void * pBuffer);
void searchInfo(void *head, void * pBuffer);
void list(void *head);
void menu( void *pBuffer );
int * quantity(void * head);
void ** front(void * head);
void ** back(void * head);
void ** next(void * node);
void ** prev(void * node);
char * name(void * node);
int * age(void * node);
char * tel(void * node);
int * choice(void * pBuffer);
char * nameSearch(void * pBuffer);